### ISSUE TITLE
Cannot read properties of undefined (reading 'exports')

### ISSUE THREAD

**Issue by nielsonlien** [zgid123/vite-module-federation-demo#1] opened 2022-06-28 16:20 UTC
Hi sir, i am trying to run your demo.
I am able to run npm serve on monoApp and npm run start on superapp.
When i access http://localhost:3000/monoApp, i am getting below error, appreciate if you can help me.

![image](https://user-images.githubusercontent.com/57793426/176230060-aa7ce549-d888-4c47-ae82-a792490286c2.png)

**Comment by zgid123** [comment] 2022-06-28 17:27
Hi, I don't think there is someone try to run this one, because this one is for reproducing the bug of `vite-module-federation` old version. I just updated the project and changed from yarn to pnpm (not sure why pnpm can run but yarn does not), so you can use to run the demo.

You should build two projects and then run `pnpm serve` for two projects.

The reason is currently, the package `vite-module-federation` cannot run the remote app in dev. And for the `superapp`, you can run it as dev (`pnpm start`). But you should follow [this one](https://github.com/originjs/vite-plugin-federation#the-remote-module-failed-to-load-the-share-of-the-local-module-for-examplelocalhost1-uncaught-in-promise-typeerror-failed-to-fetch-dynamically-imported-module-httplocalhost8080node_modulescachedirvuejsv4cd35ed0). I haven't tried it, so I'm not sure it will work or not. But if you use `pnpm serve`, it will work

**Comment by zgid123** [comment] 2022-07-01 09:43
hi @nielsonlien, if there is nothing left, I will close this issue. Feel free to reopen and ask if you have problem

**Closed as completed by zgid123** 2022-07-01 09:43 UTC
